services:
  - type: web
    name: video-splitter-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    plan: starter
    envVars:
      - key: STREAMLIT_SERVER_MAXUPLOADSIZE
        value: "2048"
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_BROWSER_GATHERUSAGESTATS
        value: "false"
